### PR TITLE
Adding Read/Write functions

### PR DESCRIPTION
**Pull request by ankit-bagdeZ**
- Added `Read` and `Write` functions along with the test cases to store and load the state of the filter

### CODE REVIEW

**Comment by ankit-bagdeZ** [comment]
@greatroar @hashbackup
Please can you provide feedback!

**Comment by ankit-bagdeZ** [comment]
@greatroar @hashbackup gentle reminder !

**Comment by greatroar** [comment]
Sorry for not responding earlier.

I'm not going to pull this as is because it doesn't fulfill my own list of desired features for dumping and loading:
* self-describing file format, with a version number so subtle changes to as 37fc72f1178914152178da833dbaaaa75601cb97 don't become catastrophic failures
* header field that can be filled in to describe the hash function
* loader that allows you to inspect the header and see if the Bloom filter is not too large (in case it comes from stream of unknown size).

I have some code for this lying around. I'll see if I can get it in a publishable state.

**Comment by greatroar** [comment]
See #5. Would that satisfy your needs?

**Comment by ankit-bagdeZ** [comment]
Thanks @greatroar
Will get back to you !

**Comment by ankit-bagdeZ** [comment]
Hey, @greatroar 
Yes, it might work for us.
A small [comment](https://github.com/greatroar/blobloom/pull/6/files#r1064545600) - Can you please check

**Comment by ankit-bagdeZ** [comment]
Closing this now!

**Pull request closed without merging**
